sudo: required
dist: trusty
language: node_js
node_js: "stable"
branches:
  only:
  - staging
script:
- npm test
services:
- mongodb
before_install:
- export CHROME_BIN=/usr/bin/google-chrome
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
after_success: npm run coverage
